//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace C19_Tracker
{
    using System;
    using System.Collections.Generic;
    
    public partial class Allapot
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Allapot()
        {
            this.Betegs = new HashSet<Beteg>();
        }
    
        public int AllapotID { get; set; }
        public System.DateTime FDatum { get; set; }
        public Nullable<int> BetegFK { get; set; }
        public int Sulyossag { get; set; }
        public bool Kohoges { get; set; }
        public bool NehezLegzes { get; set; }
        public bool Laz { get; set; }
        public bool IzVesztes { get; set; }
    
        public virtual Beteg Beteg { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Beteg> Betegs { get; set; }
    }
}
