//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace C19_Tracker
{
    using System;
    using System.Collections.Generic;
    
    public partial class Beoszta
    {
        public int BeosztasID { get; set; }
        public int OrvosFK { get; set; }
        public string Műszak { get; set; }
    
        public virtual Orvo Orvo { get; set; }
    }
}
