//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace C19_Tracker
{
    using System;
    using System.Collections.Generic;
    
    public partial class Beteg
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Beteg()
        {
            this.Agies = new HashSet<Agy>();
            this.Allapots = new HashSet<Allapot>();
        }
    
        public int BetegID { get; set; }
        public string Nev { get; set; }
        public System.DateTime Szul_Ido { get; set; }
        public string Szul_Hely { get; set; }
        public string Nem { get; set; }
        public int Taj_Szam { get; set; }
        public System.DateTime Reg_Nap { get; set; }
        public Nullable<int> OrvosFK { get; set; }
        public Nullable<int> JelenlegiAllapotFK { get; set; }
        public bool Gyogyult { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Agy> Agies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Allapot> Allapots { get; set; }
        public virtual Allapot Allapot { get; set; }
        public virtual Orvo Orvo { get; set; }
    }
}
